server:  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/examination?characterEncoding=UTF-8&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    
  jpa:    database: mysql
    
  thymeleaf:    cache: false
    
mybatis:
  type-aliases-package: online.shixun.project.dto
  mapper-locations: classpath:mapper/*Mapper.xml
  
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true